import { ServiceItem } from "../types/serviceTypes";

 export const membersData: ServiceItem[] = [
	{
		id: 1,
		title: "Aromex",
		description: "Welcome to Aromex Air, your destination for luxurious and refreshing fragrance products. We specialize in all-natural oils and stylish ultrasonic diffusers, tailored for your car, home, and business, ensuring a welcoming atmosphere and a sense of tranquility through the power of scent. Founded in 2020 by Antoine and Toby Davenport, Aromex Air has become a leading provider of high-quality fragrance products. Explore our range to transform any space into a soothing oasis.",
		bulletPoints: [
		  "All-natural oils with antibacterial properties",
		  "Luxury room and car sprays designed to eliminate odors",
		  "Ultrasonic diffusers for cars, homes, and businesses",
		  "Scents like Lavender Mist and Lemon Rain for various benefits",
		  "Owned and operated ecommerce and storefront in Lithonia, Georgia",
		  "Founded by Antoine and Toby Davenport in 2020",
		  "Natural oils promote well-being and refresh your environment"
		],
		imageUrl: "path/to/aromex-logo.png",
		link: "https://aromexair.com/"
	  }
	  ,
	{
		id: 2,
		title: "Atl Everything",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
  id: 3,
  title: "Blingspirations",
  description: "Custom Designed T-Shirts, Apparel and More",
  bulletPoints: [
    "Rhinestones for that extra sparkle",
    "Durable and stylish Vinyl designs",
    "Mix Media for creative expression",
    "Themes for Divas, Ladies, and Glam enthusiasts",
    "Faith-based inspirational designs",
    "Sports themes for fans and athletes",
    "Awareness apparel to support causes close to your heart",
    "Greek apparel for fraternities and sororities"
  ],
  imageUrl: "path/to/blingspirations-logo.png",
  link: "https://www.blingspirations.com",
},
	{
  id: 4,
  title: "Crystal Knows Beauty",
  description: "Founded by Certified Trichologist Crystal Styles Cuthpert, Crystal Knows Beauty is a brand dedicated to health, beauty, and wellness. Through extensive travel and workshops, Crystal offers in-depth knowledge on self-care, empowering individuals with the right tools for their beauty and health regimes. Emphasizing the importance of personal care, the brand also offers B'About Self Care supplements, catering to the nutritional needs of those leading busy lives.",
  bulletPoints: [
    "Certified Trichologist offering scalp and hair analysis",
    "Engages with consumers globally through workshops, expos, and seminars",
    "Founded B’About Self Care supplements for additional nutritional support",
    "Products include a range of vegan and vegetarian-friendly vitamins and supplements",
    "Committed to personal wellness and providing motivational inspiration"
  ],
  imageUrl: "path/to/crystal-knows-beauty-logo.png",
  link: "https://beaboutselfcare.com",
},
	{
    id: 5,
    title: "Crown Jewel Sentiments",
    description: "Crown Jewel Scentiments Co. is a Bath, Body, and Home product company based in Atlanta, Georgia, inspired by the special bond between mother and daughter. Our products range from scented wax candles to bath and spa products, all designed with creativity, love, and passion. Discover the 'Crown Jewel' within you with our scentsational products designed to create memorable moments.",
    bulletPoints: [
        "Soy-based, hand-poured scented wax candles",
        "Inspired by the love between mother and daughter",
        "Creatively designed fragranced candles, bath, and spa products",
        "Specialty packaging for that personal touch",
        "Wide range of products to accent any room or occasion",
        "Handcrafted gift packaging for a special personal touch",
        "Products include candles, wax melts, aroma beads, lotion bars, and more",
        "Fragrances designed for every mood, including Aloha Orchid, Black Sea, Caribbean Teakwood, and many more"
    ],
    imageUrl: "path/to/crown-jewel-sentiments-logo.png",
    link: "https://crownjewelscent.com",
}
	{
		id: 6,
		title: "Elo Vegan",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 7,
		title: "Especially Yours Cuisine",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 8,
		title: "Ginger Yums",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 9,
		title: "It's All Good And Then Some",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 10,
		title: "Jay's Gift Shop",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 11,
		title: "Kuba Kingdom",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 12,
		title: "LivelyupIcells",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 13,
		title: "Mothers Gold",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 14,
		title: "Motique",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 15,
		title: "Q Vibe Essentials",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 16,
		title: "Rage Room",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 17,
		title: "S and B Tax",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 18,
		title: "Sirrapwear",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 19,
		title: "St. Louis Collection",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 20,
		title: "Tea Amour",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 21,
		title: "Tonys Mama Spicy Hot Sauce",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 22,
		title: "Walnut Life",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
	{
		id: 23,
		title: "YOL Juice",
		description: "",
		bulletPoints: [],
		imageUrl: "",
		link: "",
	},
];
